### PR TITLE
iHotkey to switch tab

### LINKED ISSUE #122: Hotkey to switch tab

### PR DESCRIPTION
**Pull request by louislai**
Fix #122

### CODE REVIEW

**Comment by louislai** [comment]
@Rinder5 for reference

**Comment by Rinder5** [comment]
Should I wait for this to be merged first? Since a bunch of the code will change with this.

**Comment by louislai** [comment]
@Rinder5 easy way is you review this PR then can merge asap

**Review by Rinder5 — APPROVED** [review]
/╱┏╮
/╱┃┃
▉━╯┗━╮
▉┈┈┈┈┃
▉╮┈┈┈┃
╱╰━━━╯

**Pull request merged**
