### PR TITLE
Make keyword case insensitive on the user input side

### PR DESCRIPTION
**Pull request by Melvin-Tan**
#143 
The assumption of this PR is that the coder will not be an idiot and send things like "tAGS/" into the function.
Only the user input can do stupid things.

### CODE REVIEW

**Comment by louislai** [comment]
@Rinder5 can we all make use of this in our own methods?

**Comment by louislai** [comment]
@Melvin-Tan why not release that constraint/assumption as well

**Comment by Melvin-Tan** [comment]
Abit indirect to handle that additional constraint. If want then another branch bah.
In the first place if anyone of us do something weird like that, it will not pass PR anyway.
And i still got recurring task to handle.

**Comment by louislai** [comment]
okay can

**Pull request merged**
