### PR TITLE
Update user guide

### PR DESCRIPTION
**Pull request by Rinder5**
handle class complaints.

### CODE REVIEW

**Comment by Rinder5** [comment]
Do you think our command summary should be in table format? Some other groups did it that way.

**Comment by louislai** [comment]
@Rinder5 travis build failed. Yes table form would be naise

**Comment by Rinder5** [comment]
What does travis check? My gradle checkstyle tests are passing

Edit: Nvm, I see. No new line at EOF -_-

**Comment by louislai** [comment]
You can click on it the `Details` to see it. But i am pretty sure this particular issue would have been caught by ur local gradle checkstyle as well

**Comment by Rinder5** [comment]
K, should be fixed.
Btw, I figured out why my tests keep failing. My tests keep focusing on the list field instead of the textbox field. Do you know how to fix?

**Comment by louislai** [comment]
would be pretty hard to debug online. You have a video screen capture of the issue?

**Comment by Rinder5** [comment]
its not a big deal. i'll see you on friday, maybe we can fix it there

**Comment by louislai** [comment]
how exactly did the coverage decrease. This is not even code o.O

**Comment by louislai** [comment]
@Rinder5 for delete command forma might want to change `INDEX` to `INDEXES` or `INDEX(ES)`, so wont be confused witht the use of `INDEX` in other command formats

**Comment by Rinder5** [comment]
wtf

**Comment by Rinder5** [comment]
fair point, since we changed the format of it. will edit for mark also, since it has been implemented for that

**Comment by louislai** [comment]
thanks!

**Review by louislai — APPROVED** [review]

**Pull request merged**
