### PR TITLE
Make Ui reactive

### PR DESCRIPTION
**Pull request by louislai**
Here's what this PR is doing

Remove dependency of `Controller` on `Renderer`. If you change the data of `UiStore` (through `setTasks` for e.g.), `Renderer` will listen to the data changes in `UiStore` and re-render automatically (eliminating the need for a separate `renderer.render()` in `Controller`). In effect, The Observable-Observer pattern is implemented, with`UiStore` acting as a Observable, and `Renderer` as an Observer.

### CODE REVIEW

**Review by Melvin-Tan — APPROVED** [review]
Looks to me like a pretty safe merge, since the complexity seems to be reduced quite a lot.

**Comment by louislai** [comment]
Gonna wait for #123 to be merged first

**Comment by Rinder5** [comment]
what, why wait?

**Comment by louislai** [comment]
@Rinder5 coz u prolly need to change ur code after this pr gets merged. Either I do the integration work or you have to do it

**Comment by Rinder5** [comment]
ok

**Pull request merged**
